export const data = [
    {
        name: "Matematika Lanjut 1",
        year: [2023],
        major: ["Teknik Elektro"],
        img: "/wavesOpacity.svg",
        linkDrive: "",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Rangkaian Listrik 2",
        year: [2023],
        major: ["Teknik Elektro"],
        img: "/curveAsymmetrical.svg",
        linkDrive: "",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Matematika Lanjut 2",
        year: [2023],
        major: ["Teknik Elektro"],
        img: "/wavey-fingerprint.svg",
        linkDrive: "",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Matematika Diskrit",
        year: [2023],
        major: ["Teknik Elektro"],
        img: "/wavesOpacity.svg",
        linkDrive: "",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Statistika",
        year: [2023],
        major: ["Teknik Komputer"],
        img: "/curveAsymmetrical.svg",
        linkDrive: "",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Desain Rangkaian Elektronika",
        year: [2023],
        major: ["Teknik Komputer"],
        img: "/wavey-fingerprint.svg",
        linkDrive: "",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Aljabar Linear",
        year: [2024],
        major: ["Teknik Elektro"],
        img: "/wavesOpacity.svg",
        linkDrive: "https://drive.google.com/file/d/15s3fbocH4fKoqVSutu_GNm5AW15dbLD5/view?usp=drive_link",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Kalkulus",
        year: [2024],
        major: ["Teknik Elektro", "Teknik Komputer", "Teknik Biomedik"],
        img: "/wavey-fingerprint.svg",
        linkDrive: "https://drive.google.com/file/d/1XjM3AOwSifrDkTg8w8o4Xxn-ie0Ktjuj/view?usp=drive_link",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Fisika Listrik",
        year: [2024],
        major: ["Teknik Elektro", "Teknik Komputer", "Teknik Biomedik"],
        img: "/wavesOpacity.svg",
        linkDrive: "https://drive.google.com/file/d/1FE_ItHO2dfU4gwfHZqSC76OabtkBGWaA/view?usp=drive_link",
        linkZoom: "https://www.zoom.com/?lang=null",
    },
    {
        name: "Kimia Dasar",
        year: [2024],
        major: ["Teknik Biomedik"],
        img: "/wavey-fingerprint.svg",
        linkDrive: "",
        linkZoom: "https://www.zoom.com/?lang=null",
    },

]